<?xml version="1.0" encoding="utf-8"?><Database Name="database" Class="databaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=database;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="databaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="iddh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idsp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dongia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="thanhtien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idshop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="idkh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phonenumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="thoidiemdathang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tennguoinhan" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="gmail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_admin" Member="tbl_admins">
    <Type Name="tbl_admin">
      <Column Name="Username" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_header" Member="tbl_headers">
    <Type Name="tbl_header">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="phone1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tittle" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="phone2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="shortcuticon" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_menubottom" Member="tbl_menubottoms">
    <Type Name="tbl_menubottom">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenmenu" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="thutu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_menu" Member="tbl_menus">
    <Type Name="tbl_menu">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenMenu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ThuTu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idshop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="idcard" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="moblie" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="randomkey" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_product_types" Member="tbl_product_types">
    <Type Name="tbl_product_type">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="alias" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_information" Member="tbl_informations">
    <Type Name="tbl_information">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTT" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GioiThieu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="alias" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_news" Member="tbl_news">
    <Type Name="tbl_new">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TomTat" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UrlHinh" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="keyword" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="alias" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Product" Member="tbl_Products">
    <Type Name="tbl_Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UrlHinh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GiaHienTai" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MoTaCT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SLDaBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IDLoaiSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaCu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="KhuyenMai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaTuoiMoiNgay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="keyword" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="alias" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_shop" Member="tbl_shops">
    <Type Name="tbl_shop">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenshop" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="emailshop" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="phoneshop1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="thoigianlamviec1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="masodoanhnghiep" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="addressshop" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="thoigianlamviec2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phoneshop2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="longtitude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lattitude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="keyword" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>